name: ci build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ubuntu-cmake:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libprotobuf-dev protobuf-compiler libgtest-dev valgrind
    - name: update submodules
      run: git submodule update --init --recursive
    - name: make
      run: make -j4
    - name: make tutorial
      run: make tutorial -j4
    - name: make check
      run: make check -j4
    - name: make install
      run: sudo make install

  fedora-cmake:
    name: fedora
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:rawhide
      - name: Get source
        uses: actions/checkout@master
        with:
          path: 'workflow'
      - name: Create container and run tests
        run: |
          {
              echo 'FROM fedora:rawhide'
              echo 'RUN dnf -y update'
              echo 'RUN dnf -y install cmake gcc-c++ gtest-devel git make'
              echo 'RUN dnf -y install openssl-devel protobuf-devel'
              echo 'RUN dnf -y install lz4-devel snappy-devel'
              echo 'RUN dnf clean all'
              echo 'COPY workflow workflow'
              echo 'WORKDIR /workflow'
              echo 'RUN git submodule update --init --recursive'
              echo 'RUN cmake'
              echo 'RUN make'
              echo 'RUN make check'
              echo 'RUN make tutorial'
          } > podmanfile
          podman build --tag fedorarawhide -f ./podmanfile

  ubuntu-bazel:
    name: bazel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Bazel 5.4.0
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
        sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
        echo "deb [signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt-get update
        sudo apt-get install -y bazel-5.4.0

    - name: bazel build
      run: bazel build --noenable_bzlmod ...

